import { createFileRoute } from '@tanstack/react-router';
import { InformationPage } from '@/components/InformationPage';
export const Route=createFileRoute('/privacy')({head:()=>({meta:[{title:'Privacy — BraverTogether'},{name:'description',content:'How BraverTogether uses account information, support conversations and submissions.'}],links:[{rel:'canonical',href:'https://bravertogether.site/privacy'}]}),component:()=> <InformationPage title="Privacy" intro="We use information to run BraverTogether and help keep the community safe. Share only what is needed for your request." sections={[
['Information you provide','We store your account name, email and profile settings; support requests and messages; advisor applications and CVs; competition entries and uploaded essays; meeting proposals; and reports you submit. Public advisor profiles are visible to visitors when published. Private submissions and CVs are not public.'],
['Who can see it','Support conversations are available to their participants. Advisors see limited information about unassigned requests, then receive the private conversation when they accept it. Administrators review applications, competition entries and safety reports. A safety report may require an administrator to view the relevant conversation.'],
['Service providers','Supabase provides accounts, database and file storage. Authentication emails are delivered through the configured email provider, Resend. If AI assistance is enabled, Groq processes submitted contract text or relevant support conversation context. Groq may retain content for reliability and abuse monitoring for up to 30 days unless zero data retention is enabled. Do not submit personal or confidential documents to AI.'],
['Your choices about AI and video','Support AI is optional and off by default when creating a request. The Contract Decoder may send the text you submit to Groq when AI is configured; otherwise it runs a basic clause scan. We do not save pasted contract text as a document. AI replies in support conversations remain in that conversation. Video resources use YouTube privacy-enhanced embeds; playing a video connects to YouTube. Loading Google Fonts also connects to Google.'],
['Security and retention','We keep account and service records while needed to provide the service, handle submissions and resolve safety issues. Limited usage counters and security logs help prevent misuse. Retention can vary by record and any unresolved issue. We do not promise that provider backups are erased immediately when a record is deleted.'],
['Correction and deletion','You can update your profile from My Profile. To ask for other corrections, a copy of your information or deletion, sign in, open Messages and create a support request with the subject “Privacy request”. Avoid attaching identity documents. The team may need to verify account ownership before acting. If you cannot sign in, contact bravertogether31@gmail.com, the initiative’s published contact address.'],
['Young people','For serious or sensitive matters, involve a trusted adult. Never send passwords, payment information, your home address or someone else’s private details. Our service provides educational information and is not an emergency or confidential legal service.']
]} />});
