import {createFileRoute} from '@tanstack/react-router';
import {InformationPage} from '@/components/InformationPage';
export const Route=createFileRoute('/safety')({head:()=>({meta:[{title:'Safety — BraverTogether'},{name:'description',content:'Stay safe when asking questions and speaking with BraverTogether volunteers.'}],links:[{rel:'canonical',href:'https://bravertogether.site/safety'}]}),component:()=> <InformationPage title="Your safety comes first" intro="BraverTogether offers educational information about digital rights. Volunteers and AI helpers do not replace a qualified lawyer, health professional or emergency service." sections={[
['If something is urgent','If you or someone else is in immediate danger, contact local emergency services and a trusted adult. Do not wait for a platform reply. For an urgent legal deadline, seek a qualified professional in your jurisdiction.'],
['Share carefully','Do not send passwords, financial information, home addresses, confidential documents, school records or private details about other minors. Describe the issue without identifying people when possible.'],
['Keep conversations appropriate','Use the platform for relevant educational questions. Do not agree to secret conversations, payments, inappropriate requests or unwanted personal contact. You may decline a meeting or stop participating. Check meeting links before opening them and involve a trusted adult when needed.'],
['Report a concern','Use Report in the conversation to flag inappropriate conduct. Explain what happened without adding unnecessary personal details. Administrators can review the reported conversation. Closing a conversation stops further messages; reporting does not itself guarantee immediate intervention.'],
['Human help and AI','A team request waits for an approved volunteer to accept it. Replies may take time. Optional AI can explain basic terms or help prepare your question; it cannot make legal decisions or manage emergencies. AI assistance stops when a human advisor takes over.']
]} />});
