import { createFileRoute } from '@tanstack/react-router';
import { useServerFn } from '@tanstack/react-start';
import { useState } from 'react';
import { SiteLayout,Section } from '@/components/SiteLayout';
import { listReports, reportContext, resolveReport } from '@/lib/moderation.functions';
export const Route=createFileRoute('/_authenticated/admin-reports')({loader:()=>listReports(),head:()=>({meta:[{title:'Safety reports — BraverTogether'},{name:'robots',content:'noindex,nofollow'}]}),component:Reports});
function Reports(){
 const initial=Route.useLoaderData();const [reports,setReports]=useState(initial);const [error,setError]=useState('');
 const load=useServerFn(listReports);const context=useServerFn(reportContext);const save=useServerFn(resolveReport);
 const [messages,setMessages]=useState<Awaited<ReturnType<typeof reportContext>>>([]);const [selected,setSelected]=useState<string|null>(null);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);
 async function open(id:string,note:string|null){setBusy(true);setError('');setSelected(null);setMessages([]);try{const m=await context({data:{id}});setMessages(m);setSelected(id);setNote(note??'');}catch{setError('Report context could not be loaded.');}finally{setBusy(false);}}
 async function update(status:'reviewing'|'resolved'){if(!selected)return;setBusy(true);try{await save({data:{id:selected,status,note}});setReports(await load());setSelected(null);setMessages([]);}catch{setError('Report could not be saved.');}finally{setBusy(false);}}
 return <SiteLayout><Section><h1 className="text-4xl font-bold">Safety reports</h1><p className="mt-3 text-muted-foreground">Review concerns, record your response and resolve reports. Recent 100 reports are shown.</p>{error&&<p role="alert" className="mt-4 text-red-700">{error}</p>}<div className="mt-8 grid gap-6 lg:grid-cols-2"><div className="space-y-4">{reports.map(r=><article key={r.id} className="rounded-2xl border p-5"><p className="text-sm text-teal">{r.status} · {new Date(r.created_at).toLocaleDateString()}</p><p className="my-3 whitespace-pre-wrap break-words">{r.reason}</p><button disabled={busy} onClick={()=>open(r.id,r.resolution_note)} className="rounded-full border px-4 py-2">Review report</button></article>)}{!reports.length&&<p>No reports to review.</p>}</div>{selected&&<div className="min-w-0 rounded-2xl border p-5"><h2 className="text-xl font-bold">Conversation context</h2><p className="text-sm text-muted-foreground">Most recent 100 messages. Use this information only to review the report.</p><div className="my-5 max-h-96 space-y-3 overflow-auto">{messages.map(m=><p key={m.id} className="whitespace-pre-wrap break-words rounded-xl bg-secondary p-3"><span className="block text-xs text-teal">{m.sender_kind}</span>{m.body}</p>)}</div><label className="grid gap-2">Review note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} className="rounded-xl border p-3" /></label><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>update('reviewing')} className="rounded-full border px-4 py-2">Mark reviewing</button><button disabled={busy} onClick={()=>update('resolved')} className="rounded-full bg-navy px-4 py-2 text-white">Resolve</button></div></div>}</div></Section></SiteLayout>;
}
