/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as NewsRouteImport } from './routes/news'
import { Route as DecoderRouteImport } from './routes/decoder'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AdvisorSignupRouteImport } from './routes/advisor-signup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated/meetings'
import { Route as AuthenticatedEssaySubmissionRouteImport } from './routes/_authenticated/essay-submission'
import { Route as AuthenticatedAdvisorApplicationRouteImport } from './routes/_authenticated/advisor-application'
import { Route as AuthenticatedAdminCompetitionsRouteImport } from './routes/_authenticated/admin-competitions'
import { Route as AuthenticatedAdminAdvisorsRouteImport } from './routes/_authenticated/admin-advisors'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoderRoute = DecoderRouteImport.update({
  id: '/decoder',
  path: '/decoder',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorSignupRoute = AdvisorSignupRouteImport.update({
  id: '/advisor-signup',
  path: '/advisor-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEssaySubmissionRoute =
  AuthenticatedEssaySubmissionRouteImport.update({
    id: '/essay-submission',
    path: '/essay-submission',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvisorApplicationRoute =
  AuthenticatedAdvisorApplicationRouteImport.update({
    id: '/advisor-application',
    path: '/advisor-application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCompetitionsRoute =
  AuthenticatedAdminCompetitionsRouteImport.update({
    id: '/admin-competitions',
    path: '/admin-competitions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdvisorsRoute =
  AuthenticatedAdminAdvisorsRouteImport.update({
    id: '/admin-advisors',
    path: '/admin-advisors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor-signup': typeof AdvisorSignupRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/decoder': typeof DecoderRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/admin-advisors': typeof AuthenticatedAdminAdvisorsRoute
  '/admin-competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/advisor-application': typeof AuthenticatedAdvisorApplicationRoute
  '/essay-submission': typeof AuthenticatedEssaySubmissionRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor-signup': typeof AdvisorSignupRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/decoder': typeof DecoderRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/admin-advisors': typeof AuthenticatedAdminAdvisorsRoute
  '/admin-competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/advisor-application': typeof AuthenticatedAdvisorApplicationRoute
  '/essay-submission': typeof AuthenticatedEssaySubmissionRoute
  '/meetings': typeof AuthenticatedMeetingsRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/advisor-signup': typeof AdvisorSignupRoute
  '/advisors': typeof AdvisorsRoute
  '/auth': typeof AuthRoute
  '/competitions': typeof CompetitionsRoute
  '/decoder': typeof DecoderRoute
  '/news': typeof NewsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/_authenticated/admin-advisors': typeof AuthenticatedAdminAdvisorsRoute
  '/_authenticated/admin-competitions': typeof AuthenticatedAdminCompetitionsRoute
  '/_authenticated/advisor-application': typeof AuthenticatedAdvisorApplicationRoute
  '/_authenticated/essay-submission': typeof AuthenticatedEssaySubmissionRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisor-signup'
    | '/advisors'
    | '/auth'
    | '/competitions'
    | '/decoder'
    | '/news'
    | '/resources'
    | '/team'
    | '/admin-advisors'
    | '/admin-competitions'
    | '/advisor-application'
    | '/essay-submission'
    | '/meetings'
    | '/messages'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisor-signup'
    | '/advisors'
    | '/auth'
    | '/competitions'
    | '/decoder'
    | '/news'
    | '/resources'
    | '/team'
    | '/admin-advisors'
    | '/admin-competitions'
    | '/advisor-application'
    | '/essay-submission'
    | '/meetings'
    | '/messages'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/advisor-signup'
    | '/advisors'
    | '/auth'
    | '/competitions'
    | '/decoder'
    | '/news'
    | '/resources'
    | '/team'
    | '/_authenticated/admin-advisors'
    | '/_authenticated/admin-competitions'
    | '/_authenticated/advisor-application'
    | '/_authenticated/essay-submission'
    | '/_authenticated/meetings'
    | '/_authenticated/messages'
    | '/_authenticated/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdvisorSignupRoute: typeof AdvisorSignupRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AuthRoute: typeof AuthRoute
  CompetitionsRoute: typeof CompetitionsRoute
  DecoderRoute: typeof DecoderRoute
  NewsRoute: typeof NewsRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoder': {
      id: '/decoder'
      path: '/decoder'
      fullPath: '/decoder'
      preLoaderRoute: typeof DecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor-signup': {
      id: '/advisor-signup'
      path: '/advisor-signup'
      fullPath: '/advisor-signup'
      preLoaderRoute: typeof AdvisorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/essay-submission': {
      id: '/_authenticated/essay-submission'
      path: '/essay-submission'
      fullPath: '/essay-submission'
      preLoaderRoute: typeof AuthenticatedEssaySubmissionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advisor-application': {
      id: '/_authenticated/advisor-application'
      path: '/advisor-application'
      fullPath: '/advisor-application'
      preLoaderRoute: typeof AuthenticatedAdvisorApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-competitions': {
      id: '/_authenticated/admin-competitions'
      path: '/admin-competitions'
      fullPath: '/admin-competitions'
      preLoaderRoute: typeof AuthenticatedAdminCompetitionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-advisors': {
      id: '/_authenticated/admin-advisors'
      path: '/admin-advisors'
      fullPath: '/admin-advisors'
      preLoaderRoute: typeof AuthenticatedAdminAdvisorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAdvisorsRoute: typeof AuthenticatedAdminAdvisorsRoute
  AuthenticatedAdminCompetitionsRoute: typeof AuthenticatedAdminCompetitionsRoute
  AuthenticatedAdvisorApplicationRoute: typeof AuthenticatedAdvisorApplicationRoute
  AuthenticatedEssaySubmissionRoute: typeof AuthenticatedEssaySubmissionRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAdvisorsRoute: AuthenticatedAdminAdvisorsRoute,
  AuthenticatedAdminCompetitionsRoute: AuthenticatedAdminCompetitionsRoute,
  AuthenticatedAdvisorApplicationRoute: AuthenticatedAdvisorApplicationRoute,
  AuthenticatedEssaySubmissionRoute: AuthenticatedEssaySubmissionRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdvisorSignupRoute: AdvisorSignupRoute,
  AdvisorsRoute: AdvisorsRoute,
  AuthRoute: AuthRoute,
  CompetitionsRoute: CompetitionsRoute,
  DecoderRoute: DecoderRoute,
  NewsRoute: NewsRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
